version: '3.3'

services:
  client1:
    build: .
    environment:
      - TZ=American/Chicago
      - DEBIAN_FRONTEND=noninteractive
    hostname: client1
    container_name: client1
    networks:
      - default
  client2:
    build: .
    environment:
      - TZ=American/Chicago
      - DEBIAN_FRONTEND=noninteractive
    hostname: client2
    container_name: client2
    networks:
      - default
  client3:
    build: .
    environment:
      - TZ=American/Chicago
      - DEBIAN_FRONTEND=noninteractive
    hostname: client3
    container_name: client3
    networks:
      - default
  client4:
    build: .
    environment:
      - TZ=American/Chicago
      - DEBIAN_FRONTEND=noninteractive
    hostname: client4
    container_name: client4
    networks:
      - default
  client5:
    build: .
    environment:
      - TZ=American/Chicago
      - DEBIAN_FRONTEND=noninteractive
    hostname: client5
    container_name: client5
    networks:
      - default

networks:
  default:
    driver: bridge