# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mutualStore_pb2 as mutualStore__pb2


class SecureMessagingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreBlock = channel.unary_unary(
                '/SecureMessaging/StoreBlock',
                request_serializer=mutualStore__pb2.StoreReq.SerializeToString,
                response_deserializer=mutualStore__pb2.Confirmation.FromString,
                )
        self.RetrieveBlock = channel.unary_unary(
                '/SecureMessaging/RetrieveBlock',
                request_serializer=mutualStore__pb2.RetrieveReq.SerializeToString,
                response_deserializer=mutualStore__pb2.BlockMsg.FromString,
                )
        self.JoinNode = channel.unary_unary(
                '/SecureMessaging/JoinNode',
                request_serializer=mutualStore__pb2.JoinReq.SerializeToString,
                response_deserializer=mutualStore__pb2.Confirmation.FromString,
                )


class SecureMessagingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecureMessagingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreBlock,
                    request_deserializer=mutualStore__pb2.StoreReq.FromString,
                    response_serializer=mutualStore__pb2.Confirmation.SerializeToString,
            ),
            'RetrieveBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveBlock,
                    request_deserializer=mutualStore__pb2.RetrieveReq.FromString,
                    response_serializer=mutualStore__pb2.BlockMsg.SerializeToString,
            ),
            'JoinNode': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNode,
                    request_deserializer=mutualStore__pb2.JoinReq.FromString,
                    response_serializer=mutualStore__pb2.Confirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SecureMessaging', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecureMessaging(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecureMessaging/StoreBlock',
            mutualStore__pb2.StoreReq.SerializeToString,
            mutualStore__pb2.Confirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecureMessaging/RetrieveBlock',
            mutualStore__pb2.RetrieveReq.SerializeToString,
            mutualStore__pb2.BlockMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SecureMessaging/JoinNode',
            mutualStore__pb2.JoinReq.SerializeToString,
            mutualStore__pb2.Confirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
